ControleDeEstoque.Web/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Web.Controllers
{
    public class CadastroController : Controller
    {
        // GET: Cadastro
        public ActionResult GrupoProduto()
        {
            return View();
        }
        public ActionResult MarcaProduto()
        {
            return View();
        }
        public ActionResult LocalProduto()
        {
            return View();
        }
        public ActionResult UnidadeMedida()
        {
            return View();
        }
        public ActionResult Produto()
        {
            return View();
        }
        public ActionResult Pais()
        {
            return View();
        }
        public ActionResult Estado()
        {
            return View();
        }
        public ActionResult Cidade()
        {
            return View();
        }
        public ActionResult PerfilUsuario()
        {
            return View();
        }
        public ActionResult Usuario()
        {
            return View();
        }
    }
}

ControleDeEstoque.Web/Controllers/GraficoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Web.Controllers
{
    public class GraficoController : Controller
    {
        // GET: Grafico
        public ActionResult PerdaMes()
        {
            return View();
        }
        public ActionResult EntradaSaidaMes()
        {
            return View();
        }
    }
}

ControleDeEstoque.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Sobre()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

    }
}

ControleDeEstoque.Web/Controllers/OperacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Web.Controllers
{
    public class OperacaoController : Controller
    {
        // GET: Operacao
        public ActionResult EntradaEstoque()
        {
            return View();
        }
        public ActionResult SaidaEstoque()
        {
            return View();
        }
        public ActionResult LancaPerdaProduto()
        {
            return View();
        }
        public ActionResult Inventario()
        {
            return View();
        }

    }
}

ControleDeEstoque.Web/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Web.Controllers
{
    public class RelatorioController : Controller
    {
        // GET: Relatorio
        public ActionResult PosicaoEstoque()
        {
            return View();
        }
        public ActionResult Ressuprimento()
        {
            return View();
        }
    }
}

ControleDeEstoque.Web/Views/Cadastro/Cidade.cshtml
<h2>Cidade</h2>

ControleDeEstoque.Web/Views/Cadastro/Estado.cshtml
<h2>Estado</h2>

ControleDeEstoque.Web/Views/Cadastro/GrupoProduto.cshtml
<h2>GrupoProduto</h2>

ControleDeEstoque.Web/Views/Cadastro/LocalProduto.cshtml
<h2>LocalProduto</h2>

ControleDeEstoque.Web/Views/Cadastro/MarcaProduto.cshtml
<h2>MarcaProduto</h2>

ControleDeEstoque.Web/Views/Cadastro/Pais.cshtml
<h2>Pais</h2>

ControleDeEstoque.Web/Views/Cadastro/PerfilUsuario.cshtml
<h2>Perfil Usuario</h2>

ControleDeEstoque.Web/Views/Cadastro/Produto.cshtml
<h2>Produto</h2>

ControleDeEstoque.Web/Views/Cadastro/UnidadeMedida.cshtml
<h2>UnidadeMedida</h2>

ControleDeEstoque.Web/Views/Cadastro/Usuario.cshtml
<h2>Usuario</h2>

ControleDeEstoque.Web/Views/Grafico/EntradaSaidaMes.cshtml
<h2>Entrada e Saida Mes</h2>

ControleDeEstoque.Web/Views/Grafico/PerdaMes.cshtml
<h2>PerdaMes</h2>

ControleDeEstoque.Web/Views/Home/Sobre.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title o Controle de Estoque. </h2>

ControleDeEstoque.Web/Views/Operacao/EntradaEstoque.cshtml
<h2>EntradaEstoque</h2>

ControleDeEstoque.Web/Views/Operacao/Inventario.cshtml
<h2>Inventario</h2>

ControleDeEstoque.Web/Views/Operacao/LancaPerdaProduto.cshtml
<h2>Lanca Perda Produto</h2>

ControleDeEstoque.Web/Views/Operacao/SaidaEstoque.cshtml
<h2>Saida Estoque</h2>

ControleDeEstoque.Web/Views/Relatorio/PosicaoEstoque.cshtml
<h2>PosicaoEstoque</h2>

ControleDeEstoque.Web/Views/Relatorio/Ressuprimento.cshtml
<h2>Ressuprimento</h2>

ControleDeEstoque.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle de Estoque</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de Estoque", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Cadastros
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Grupo de Produtos", "GrupoProduto", "Cadastro")</li>
                            <li>@Html.ActionLink("Marca de Produtos", "MarcaProduto", "Cadastro")</li>
                            <li>@Html.ActionLink("Locais Armazenados", "LocalProduto", "Cadastro")</li>
                            <li>@Html.ActionLink("Unidades de Medida", "UnidadeMedida", "Cadastro")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Produtos", "Produto", "Cadastro")</li>
                            <li>@Html.ActionLink("Países", "Pais", "Cadastro")</li>
                            <li>@Html.ActionLink("Estados", "Estado", "Cadastro")</li>
                            <li>@Html.ActionLink("Cidades", "Cidade", "Cadastro")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Perfis de Usuários", "PerfilUsuario", "Cadastro")</li>
                            <li>@Html.ActionLink("Usuários", "Usuario", "Cadastro")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Operações
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Entrada de produtos", "EntradaEstoque", "Operacao")</li>
                            <li>@Html.ActionLink("Saída de produtos", "SaidaEstoque", "Operacao")</li>
                            <li>@Html.ActionLink("Lançamento de Perdas de produtos", "LancaPerdaProduto", "Operacao")</li>
                            <li>@Html.ActionLink("Inventário de Estoque", "Inventario", "Operacao")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Relátorios
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Posição do Estoque", "PosicaoEstoque", "Relatorio")</li>
                            <li>@Html.ActionLink("Ressuprimento", "Ressuprimento", "Relatorio")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Gráficos
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Perdas por mês", "PerdaMes", "Grafico")</li>
                            <li>@Html.ActionLink("Entradas vs saídas por mês","EntradaSaidaMes", "Grafico")</li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right ">
                    <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle de Estoque</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>